name: CI
on: 
  push:
    branches:
      main
  pull_request:
jobs:
  flake-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build
